### PR TITLE
PP-5761 Add PAYMENT_EXTERNAL_ID logging key

### PR DESCRIPTION
**Pull request by danworth**

### CODE REVIEW

**Comment by alexbishop1** [comment]
Can we call it `PAYMENT_EXTERNAL_ID` because we generally prefer “payment” to “charge”?

**Comment by danworth** [comment]
@alexbishop1 yes we can and I've updated it

**Comment by stephencdaly** [comment]
How about `transaction_external_id` as this will probably work better for ledger where payments and refunds are both transactions? It would be good if the keys are consistent between the services with minimal effort

**Comment by stephencdaly** [comment]
Actually I've changed my mind as we might have a case where we want to log both a refund external id and a payment external id in the same log line. Ledger can just work differently.

**Comment by danworth** [comment]
As discussed wrt using `transaction_external_id` we may wish to add both `refund_external_id` and `payment_external_id` so there's a benefit in keeping these keys distinct for now.

**Pull request merged**
